default:
  image: ${DOCKER_IMAGE}

stages:
  - build

build-code:
  stage: build
  script:
    - git clone https://oauth2:${GIT_CREDENTIAL}@git.ucsc.edu/${GIT_REPO}.git
    - cd ci/grading/
    - git submodule init
    - git submodule update
    - cd ..
    - python3 ci.py
  rules:
    - when: manual
