default:
  image: ${DOCKER_IMAGE}

stages:
  - build

build-code:
  stage: build
  script:
    - git clone --recurse-submodules https://oauth2:${GIT_CREDENTIAL}@git.ucsc.edu/${GIT_REPO}.git
    - cd ci/
    - cd grading
    - ls || echo
    - cd ..
    - python3 ci.py
  rules:
    - when: manual
