default:
  image: ${DOCKER_IMAGE}

stages:
  - build

build-code:
  stage: build
  script:
    - echo "print('hello')" > test.py
    - python3 test.py
   # - cd ${SERVER} && python3 ci.py
  rules:
    - when: manual
