default:
  image: ${DOCKER_IMAGE}

stages:
  - build

build-code:
  stage: build
  script:
    - git clone https://${GIT_USER}:${GIT_CREDENTIAL}@github.com/${GIT_REPO}.git
    - echo "print('hello')" > test.py
    - python3 test.py
   # - cd ${SERVER} && python3 ci.py
  rules:
    - when: manual
